[package]
name = "phod"
description = "physical modelling playground"
version = "0.0.1"
edition = "2021"

# TODO:
# Shaders in raylib
# Approximate ui
# Create Lowpass and Highpass filters

[dependencies]
raylib = "3.7.0"
cpal = "0.15.0"
crossbeam-utils = "0.8.15"
